### ISSUE TITLE
Ginga install required extra installation of PySide6

### ISSUE THREAD

**Issue by bmorris3** [ejeschke/ginga#1043]
I tried `pip install ginga` today. I'm using py3.10.9 and ginga 4.0.1, on an M1 Mac with OS X 12.6. 

The install ran without issues, but running `$ ginga` yielded:
```
Traceback (most recent call last):
  File "/Users/bmmorris/miniconda3/envs/research3/lib/python3.10/site-packages/qtpy/__init__.py", line 252, in <module>
    from PySide6 import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bmmorris/miniconda3/envs/research3/bin/ginga", line 8, in <module>
    sys.exit(_main())
  File "/Users/bmmorris/miniconda3/envs/research3/lib/python3.10/site-packages/ginga/rv/main.py", line 746, in _main
    reference_viewer(sys.argv)
  File "/Users/bmmorris/miniconda3/envs/research3/lib/python3.10/site-packages/ginga/rv/main.py", line 741, in reference_viewer
    viewer.main(options, args)
  File "/Users/bmmorris/miniconda3/envs/research3/lib/python3.10/site-packages/ginga/rv/main.py", line 385, in main
    ginga_toolkit.choose()
  File "/Users/bmmorris/miniconda3/envs/research3/lib/python3.10/site-packages/ginga/toolkit.py", line 73, in choose
    from ginga.qtw import QtHelp  # noqa
  File "/Users/bmmorris/miniconda3/envs/research3/lib/python3.10/site-packages/ginga/qtw/QtHelp.py", line 42, in <module>
    from qtpy import QtCore
  File "/Users/bmmorris/miniconda3/envs/research3/lib/python3.10/site-packages/qtpy/__init__.py", line 259, in <module>
    raise QtBindingsNotFoundError()
qtpy.QtBindingsNotFoundError: No Qt bindings could be found
```

After running `pip install PySide6`, the issues were resolved and ginga opened successfully.

**Comment by pllim** [comment]
Huh, you should have Qt by default?

https://github.com/ejeschke/ginga/blob/af1756aa0fb9bda485fee2e1706836382d60547b/setup.cfg#L50

**Comment by ejeschke** [comment]
It's not set as required in `setup.cfg` because it is possible to use other back ends, like Gtk.  I wonder how matplotlib takes care of choosing which one to install--maybe tries a few imports to see what is available during the install?

**Comment by ejeschke** [comment]
@pllim, installing `qtpy` does not force a PyQt or PySide installation.

**Comment by ejeschke** [comment]
However, most people will want `matplotlib` installed in order to see the plots, so once that is installed you have one of the back ends available.

**Comment by pllim** [comment]
Matplotlib has some fancy stuff but I got lost here:

https://github.com/matplotlib/matplotlib/blob/60f01751c0bfb486dec45faf1c494e4c1042f236/lib/matplotlib/rcsetup.py#L244

**Comment by eas342** [comment]
I tried pip installing `stginga` and had a similar issue with qt on an M1 mac Python 3.12.0.

(stginga) % stginga
UI toolkit choose error: qt or gtk variants not found
(stginga) % ginga
UI toolkit choose error: qt or gtk variants not found

`conda install PyQt` fixed this issue for me

**Comment by ejeschke** [comment]
Recommend installing by:
```bash
pip install ginga[qt5]
```
 or
```bash
pip install ginga[qt6]
```
Closing, we can revisit later if a reasonable solution is found.
