### ISSUE TITLE
Missing menubar_w

### ISSUE THREAD

**Issue by stscieisenhamer** [ejeschke/ginga#233]
With latest master, I get the following. And note: changing `menubar_w` to `menubar` at least gets ginga to run, but the menubar still does not appear.

```
No handlers could be found for logger "ginga"
Traceback (most recent call last):
  File "/Users/eisenham/anaconda/envs/stginga_py2/bin/ginga", line 4, in <module>
    __import__('pkg_resources').run_script('ginga==2.5.20151117213001', 'ginga')
  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 735, in run_script

  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 1652, in run_script

  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/ginga-2.5.20151117213001-py2.7.egg/EGG-INFO/scripts/ginga", line 14, in <module>
    main.reference_viewer(sys.argv)
  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/ginga-2.5.20151117213001-py2.7.egg/ginga/main.py", line 539, in reference_viewer
    viewer.main(options, args)
  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/ginga-2.5.20151117213001-py2.7.egg/ginga/main.py", line 379, in main
    ginga.build_toplevel()
  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/ginga-2.5.20151117213001-py2.7.egg/ginga/gw/GingaGw.py", line 144, in build_toplevel
    self.w.menubar = self.add_menus(menuholder)
  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/ginga-2.5.20151117213001-py2.7.egg/ginga/gw/GingaGw.py", line 173, in add_menus
    self.w['top'].add_widget(menubar_w, stretch=0)
NameError: global name 'menubar_w' is not defined
```

**Comment by pllim** [comment]
#234 should fix this, as you mentioned in spacetelescope/stginga#50.
