### ISSUE TITLE
Failures with Numpy dev

### ISSUE THREAD

**Issue by astrofrog** [ejeschke/ginga#267]
There are test failures (and failures when trying to run ginga) with the latest Numpy dev version:

```python
running test
running egg_info
creating ginga.egg-info
writing requirements to ginga.egg-info/requires.txt
writing ginga.egg-info/PKG-INFO
writing top-level names to ginga.egg-info/top_level.txt
writing dependency_links to ginga.egg-info/dependency_links.txt
writing manifest file 'ginga.egg-info/SOURCES.txt'
reading manifest file 'ginga.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ginga.egg-info/SOURCES.txt'
running build_ext
test_pan (ginga.tests.test_ImageView.TestImageView) ... /Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/Bindings.py:274: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  self.logger.warn("No method found matching '%s'" % (name))
No method found matching 'kp_edit_del'
No method found matching 'ms_none'
No method found matching 'kp_poly_del'
No method found matching 'gs_tap'
No method found matching 'ms_draw'
No method found matching 'ms_wheel'
No method found matching 'gs_swipe'
No method found matching 'ms_cursor'
No method found matching 'kp_poly_add'
Failed to initialize image: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
Traceback:
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/ImageView.py", line 745, in set_image
    self.auto_levels()
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/ImageView.py", line 2218, in auto_levels
    loval, hival = autocuts.calc_cut_levels(image)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/AutoCuts.py", line 405, in calc_cut_levels
    num_points=self.num_points)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/AutoCuts.py", line 424, in calc_zscale
    loval, hival = zscale.zscale_samples(samples, contrast=contrast)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/util/zscale.py", line 83, in zscale_samples
    median = 0.5 * (samples[center_pixel] + samples[center_pixel + 1])

ERROR
test_scale (ginga.tests.test_ImageView.TestImageView) ... No method found matching 'kp_edit_del'
No method found matching 'ms_none'
No method found matching 'kp_poly_del'
No method found matching 'gs_tap'
No method found matching 'ms_draw'
No method found matching 'ms_wheel'
No method found matching 'gs_swipe'
No method found matching 'ms_cursor'
No method found matching 'kp_poly_add'
Failed to initialize image: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
Traceback:
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/ImageView.py", line 745, in set_image
    self.auto_levels()
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/ImageView.py", line 2218, in auto_levels
    loval, hival = autocuts.calc_cut_levels(image)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/AutoCuts.py", line 405, in calc_cut_levels
    num_points=self.num_points)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/AutoCuts.py", line 424, in calc_zscale
    loval, hival = zscale.zscale_samples(samples, contrast=contrast)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/util/zscale.py", line 83, in zscale_samples
    median = 0.5 * (samples[center_pixel] + samples[center_pixel + 1])

ERROR
test_01 (ginga.tests.test_Task.TestTask01) ... ok
test_02 (ginga.tests.test_Task.TestTask01) ... ok
test_03 (ginga.tests.test_Task.TestTask01) ... ok
test_04 (ginga.tests.test_Task.TestTask01) ... ok
test_05 (ginga.tests.test_Task.TestTask01) ... ok
test_06 (ginga.tests.test_Task.TestTask01) ... ok
test_07 (ginga.tests.test_Task.TestTask01) ... ok
test_08 (ginga.tests.test_Task.TestTask01) ... ok
test_pixtoradec_scalar_astlib (ginga.tests.test_wcs.TestImageView) ... ok
test_pixtoradec_scalar_astropy (ginga.tests.test_wcs.TestImageView) ... WARNING: FITSFixedWarning: RADECSYS= 'FK5 ' 
the RADECSYS keyword is deprecated, use RADESYSa. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'unitfix' made the change 'Changed units: 'degree  ' -> 'deg', 'degree  ' -> 'deg''. [astropy.wcs.wcs]
ok
test_pixtoradec_scalar_kapteyn (ginga.tests.test_wcs.TestImageView) ... ok
test_pixtoradec_scalar_starlink (ginga.tests.test_wcs.TestImageView) ... ok
test_radectopix_scalar_astlib (ginga.tests.test_wcs.TestImageView) ... ok
test_radectopix_scalar_astropy (ginga.tests.test_wcs.TestImageView) ... ok
test_radectopix_scalar_kapteyn (ginga.tests.test_wcs.TestImageView) ... ok
test_radectopix_scalar_starlink (ginga.tests.test_wcs.TestImageView) ... ok

======================================================================
ERROR: test_pan (ginga.tests.test_ImageView.TestImageView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/tests/test_ImageView.py", line 35, in test_pan
    viewer.set_image(self.image)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/ImageView.py", line 758, in set_image
    raise e
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/ImageView.py", line 745, in set_image
    self.auto_levels()
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/ImageView.py", line 2218, in auto_levels
    loval, hival = autocuts.calc_cut_levels(image)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/AutoCuts.py", line 405, in calc_cut_levels
    num_points=self.num_points)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/AutoCuts.py", line 424, in calc_zscale
    loval, hival = zscale.zscale_samples(samples, contrast=contrast)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/util/zscale.py", line 83, in zscale_samples
    median = 0.5 * (samples[center_pixel] + samples[center_pixel + 1])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: test_scale (ginga.tests.test_ImageView.TestImageView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/tests/test_ImageView.py", line 23, in test_scale
    viewer.set_image(self.image)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/ImageView.py", line 758, in set_image
    raise e
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/ImageView.py", line 745, in set_image
    self.auto_levels()
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/ImageView.py", line 2218, in auto_levels
    loval, hival = autocuts.calc_cut_levels(image)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/AutoCuts.py", line 405, in calc_cut_levels
    num_points=self.num_points)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/AutoCuts.py", line 424, in calc_zscale
    loval, hival = zscale.zscale_samples(samples, contrast=contrast)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/ginga-2.5.20151230025145-py3.4.egg/ginga/util/zscale.py", line 83, in zscale_samples
    median = 0.5 * (samples[center_pixel] + samples[center_pixel + 1])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

----------------------------------------------------------------------
Ran 18 tests in 8.312s

FAILED (errors=2)
WCS 'astlib' not available--skipping test
WCS 'kapteyn' not available--skipping test
WCS 'starlink' not available--skipping test
WCS 'astlib' not available--skipping test
WCS 'kapteyn' not available--skipping test
WCS 'starlink' not available--skipping test
```

**Comment by pllim** [comment]
Could be because of this -- http://docs.scipy.org/doc/numpy-dev/release.html#deprecated-to-error

**Comment by ejeschke** [comment]
@astrofrog can you tell us a little bit more about which version you are using?  I just checked out numpy from https://github.com/numpy/numpy.git and built it.
```python
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from numpy import __version__
>>> __version__
'1.11.0.dev0+4b82b1b'
```
This version seems to be work fine with python 2.7 under linux.  I will test with python 3 shortly.

**Comment by ejeschke** [comment]
python3 seems also ok with ginga and this version of numpy.

**Comment by astrofrog** [comment]
I updated all my repos and it now works, so it might have been a temporary failure in Numpy. I'll re-open if I see the issue again.

**Comment by ejeschke** [comment]
Tnx!

**Comment by ejeschke** [comment]
@astrofrog, I am now seeing the issue after removing my preferences.  At least I see it with python 3 if the default autocuts is set to "zscale".  From the traceback (which looks similar to yours) it looks like the  problem is in the zscale implementation.

**Comment by ejeschke** [comment]
Which is [here](https://github.com/ejeschke/ginga/blob/master/ginga/util/zscale.py).

**Comment by ejeschke** [comment]
Found it.  Fix coming shortly.

**Comment by ejeschke** [comment]
Good catch @astrofrog.  This was a python 3 issue, change in division operator semantics.  There is a fix in commit 4ebef462e981fa09e8749dbcb027f3e22339fed7.

**Comment by ejeschke** [comment]
@astrofrog, this should be fixed, but please open again if you are still seeing the error.

**Comment by astrofrog** [comment]
@ejeschke - ok, thanks!
