### ISSUE TITLE
ginga installation error: no attribute githash

### ISSUE THREAD

**Issue by tiffanyhsyu** [ejeschke/ginga#700]
Hi everyone,

I have the latest version of ginga cloned and am getting this error when doing python setup.py install:

`Traceback (most recent call last):
  File "/Users/thsyu/Software/ginga/astropy_helpers/astropy_helpers/version_helpers.py", line 236, in generate_version_py
    last_githash = version_module._last_githash
AttributeError: module 'ginga.version' has no attribute '_last_githash'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    get_debug_option(PACKAGENAME))
  File "/Users/thsyu/Software/ginga/astropy_helpers/astropy_helpers/version_helpers.py", line 238, in generate_version_py
    last_githash = version_module.githash
AttributeError: module 'ginga.version' has no attribute 'githash'`

Has anyone come across this and/or have a fix? Thanks!
Tiffany

**Comment by ejeschke** [comment]
Hi Tiffany,

Does [this issue](https://github.com/ejeschke/ginga/issues/340) help?

**Comment by tiffanyhsyu** [comment]
Yes, thank you!!
