### ISSUE TITLE
Errors when Contents global plugin is disabled

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#72]
So, for my own reasons, I decided to disabled the built-in `Contents` global plugin and write my own modified version. I disabled it like this:
```
from ginga import main as gmain

def main():
    # stuff

    for plg in gmain.global_plugins:
        if plg['tab'] == 'Contents':
            plg['start'] = False

    # more stuff
```

Then, I notice error messages in the log file, as follow (I am only reporting the errors that seem relevant to my change above):
```
2015-02-03 13:09:41,450 | I | main.py:428 (main) | Entering mainloop...
2015-02-03 13:09:41,484 | I | Control.py:474 (load_image) | Loading image from image1.fits
2015-02-03 13:09:41,493 | I | Control.py:474 (load_image) | Loading image from image2.fits
2015-02-03 13:09:41,953 | E | Callback.py:86 (make_callback) | Error making callback 'add-image': 'Contents' object has no attribute 'treeview'
2015-02-03 13:09:41,955 | E | Callback.py:87 (make_callback) | Traceback:
  File ".../lib/python2.7/site-packages/ginga-2.1.20141220052723-py2.7.egg/ginga/misc/Callback.py", line 70, in make_callback
    res = method(*cb_args, **cb_kwdargs)

  File ".../lib/python2.7/site-packages/ginga-2.1.20141220052723-py2.7.egg/ginga/qtw/plugins/Contents.py", line 128, in add_image
    chitem = QtGui.QTreeWidgetItem(self.treeview, [chname])

2015-02-03 13:09:41,964 | I | Control.py:798 (_switch_image) | Update image start
2015-02-03 13:09:41,965 | I | Control.py:803 (_switch_image) | Setting image...
2015-02-03 13:09:42,070 | I | Control.py:822 (_switch_image) | Large image update: 0.1044 sec
2015-02-03 13:09:42,485 | E | Callback.py:86 (make_callback) | Error making callback 'add-image': 'Contents' object has no attribute 'treeview'
2015-02-03 13:09:42,487 | E | Callback.py:87 (make_callback) | Traceback:
  File ".../lib/python2.7/site-packages/ginga-2.1.20141220052723-py2.7.egg/ginga/misc/Callback.py", line 70, in make_callback
    res = method(*cb_args, **cb_kwdargs)

  File ".../lib/python2.7/site-packages/ginga-2.1.20141220052723-py2.7.egg/ginga/qtw/plugins/Contents.py", line 128, in add_image
    chitem = QtGui.QTreeWidgetItem(self.treeview, [chname])
```

Your documentation claims that Ginga is very flexible and I should be able to enable/disable any plugins I wish. So, why am I getting these errors? How do I fix this? Thanks.

**Comment by ejeschke** [comment]
@pllim, I think the problem is that the way you are doing this only prevents ginga from starting the gui when the program starts, but the plugin is still loaded, and its constructor will run when ginga starts, which will cause it to register for new files that are loaded.  I can fix this particular error message by setting a flag when the gui is created or discarded, but if you want to disable the plugin completely I think it would be better to not load it at all.

Proceeding along the path that it looks like you are taking, how about:

    def locate_plugin(l, name):
        for plg in l:
            if plg.module == name: return plg

    pl = locate_plugin(gmain.global_plugins, 'Contents')
    gmain.global_plugins.remove(pl)

You could also just replace the list of global plugins with your own list.  There's probably a more elegant solution like:

gmain.remove_plugin('Contents')

or 

gmain.disable_plugin('Contents')

Feel free to send me a PR or if you want I can look into that.

Cheers,
~E

**Comment by ejeschke** [comment]
In commit 926662c0cdeebd7f002e41a22d61e713f8e30e14 I've added the flag described above.  Let me know if this fixes the issue with your original code.

**Comment by pllim** [comment]
Thanks, your fix works. But like you said, the proper way is to not load it at all. I appreciate the help!

**Comment by ejeschke** [comment]
@pllim, now that you know about the local and global plugin tables, you may want to look at the layout table, which specifies how the reference viewer puts together the GUI.  By customizing these three tables (which you can do by subclassing ReferenceViewer from ginga.main you can create a completely different looking viewer with a custom mix of plugins.

**Comment by pllim** [comment]
I have a problem now where my custom `ContentsManager` that inherits from `Contents` will reload the original data when I switch images via its ToC (the data was modified via a local plugin and was displayed with `set_data()`). I am not sure how to best go about this. Hope you could advise. Thanks.

**Comment by pllim** [comment]
@ejeschke , regarding the layout table, it does not seem to work with custom plugins loaded from command lines. For example, if I have a global plugin that replaces `Header`on the left, I am unable to place my replacement plugin where `Header` used to be.

**Comment by ejeschke** [comment]
Hi @pllim, the command line plugin loading is really only designed for testing plugins as they are being written, or for loading them the occasional time.  For plugins that will be used regularly it was my thinking that they really should be added via a table or API call. I think the command line loading loop assumes that all local plugins will get loaded as tabs in "Dialogs" and all global plugins (loaded with --modules) are loaded into "Right".

If you don't want to make a new top level start script, you can customize by adding a ginga_config.py file to your $HOME/.ginga directory.  This module should have two functions defined:

    def pre_gui_config(ginga):
        pass

    def post_gui_config(ginga):
        pass

These will be run before and after the GUI is initialized.  You can replace the layout table, or modify the plugin tables, etc. using these two functions.  For example, to add a custom local plugin "Foo":

    def pre_gui_config(ginga):
        spec = Bunch.Bunch(module='Foo', ws='dialogs')
        ginga.add_local_plugin(spec)

There is also a add_global_plugin function.  See ginga/main.py for details.

**Comment by ejeschke** [comment]
Regarding the issue with the subclass ContentsManager, there are couple of things to think about:
1. the ginga widget uses a ginga.misc.Datasrc object to store the images that are cycling through the channel.  This object is kind of like a bounded queue which can also be accessed in a indexed or mapped fashion.  By default, only a certain number of images are retained in this before they "age out" and are removed.  Once aged out, the reference viewer has to reload the data from the file--if the file hasn't been updated, it will load the old contents.  It's possible to increase the default number of images stored in the datasrc object, but it will increase memory usage correspondingly.

2. You can override the switch_image() method in your class, which is the method that is actually called to load the image from the contents.  This would give you the ultimate flexibility in how to handle loads from the contents.  Check the method out in the Contents plugin to see what it does.  Essentially you would just want to call set_image() on the viewer associated with the channel for the entry they clicked on.  (Contents is different from Thumbs in that it organizes the images by Channel, and by sort order).

Let me know if any of this is still unclear.

**Comment by pllim** [comment]
Thanks. Based on your example above, where is `Foo.py` supposed to reside? Ginga cannot seem to find it. I have `Foo.py` installed under my own program and I try to do this within `$HOME/.ginga/ginga_config.py`:
```
import ginga
from ginga.misc.Bunch import Bunch

from myprogram.Foo import Foo


def pre_gui_config(ginga):
    ginga.add_global_plugin(
        Bunch(module='Foor', tab='Foo', ws='right'))


def post_gui_config(ginga):
    pass
```

**Comment by pllim** [comment]
Edit: I found out that I still need to store the custom plugins in `${HOME}/.ginga/plugins/` but now I have another problem. This is my `ginga_config.py`:
```
from ginga.misc.Bunch import Bunch


def pre_gui_config(ginga):
    # Global plugins
    ginga.add_global_plugin(Bunch(module='ContentsManager', ws='right'))
    ginga.add_global_plugin(Bunch(module='History', ws='right'))

    # Local plugins
    ginga.add_local_plugin(Bunch(module='BackgroundSub', ws='dialogs'))


def post_gui_config(ginga):
    pass
```

And this are the errors:
```
2015-02-10 16:20:27,834 | I | ModuleManager.py:40 (loadModule) | Loading module 'ContentsManager'...
2015-02-10 16:20:27,842 | I | PluginManager.py:67 (loadPlugin) | Plugin 'ContentsManager' loaded.
2015-02-10 16:20:27,843 | E | Control.py:391 (add_global_plugin) | Unable to load global plugin 'ContentsManager': 'menubar'
2015-02-10 16:20:27,844 | I | ModuleManager.py:40 (loadModule) | Loading module 'History'...
2015-02-10 16:20:27,848 | I | PluginManager.py:67 (loadPlugin) | Plugin 'History' loaded.
2015-02-10 16:20:27,849 | E | Control.py:391 (add_global_plugin) | Unable to load global plugin 'History': 'menubar'
2015-02-10 16:20:27,851 | I | ModuleManager.py:40 (loadModule) | Loading module 'BackgroundSub'...
2015-02-10 16:20:27,853 | E | Control.py:373 (add_local_plugin) | Unable to load local plugin 'BackgroundSub': 'operation'
2015-02-10 16:20:28,036 | I | ModuleManager.py:40 (loadModule) | Loading module 'Toolbar'...
2015-02-10 16:20:28,061 | I | PluginManager.py:67 (loadPlugin) | Plugin 'Toolbar' loaded.
```

**Comment by ejeschke** [comment]
I think you have found an issue that needs to be fixed in ginga.

If you move these statements to post_gui_config() it should work, but it might be too late for the global plugins to get started in the GUI at program startup.  Give it a try and let me know the result.  If they don't appear at program startup time, are they (the global plugins) able to be started from the Plugins menu?

**Comment by pllim** [comment]
When I use `post_gui_config()` as you suggested, I don't see errors in log file and the global plugins appear on the GUI. However, when I select my local plugin from the menu to bring it up, I see this traceback on the terminal (not in the log file):
```
Traceback (most recent call last):
  File ".../lib/python2.7/site-packages/ginga-2.2.20150205225049-py2.7.egg/ginga/qtw/GingaQt.py", line 328, in <lambda>
    item.triggered.connect(lambda: self.start_operation_cb(title))
  File ".../lib/python2.7/site-packages/ginga-2.2.20150205225049-py2.7.egg/ginga/qtw/GingaQt.py", line 798, in start_operation_cb
    return self.start_local_plugin(chname, name, None)
  File ".../lib/python2.7/site-packages/ginga-2.2.20150205225049-py2.7.egg/ginga/Control.py", line 343, in start_local_plugin
    opmon.start_plugin_future(chinfo.name, opname, future)
  File ".../lib/python2.7/site-packages/ginga-2.2.20150205225049-py2.7.egg/ginga/misc/PluginManager.py", line 200, in start_plugin_future
    pInfo = self.getPluginInfo(opname)
  File ".../lib/python2.7/site-packages/ginga-2.2.20150205225049-py2.7.egg/ginga/misc/PluginManager.py", line 80, in getPluginInfo
    pInfo = self.plugin[plname]
  File ".../lib/python2.7/site-packages/ginga-2.2.20150205225049-py2.7.egg/ginga/misc/Bunch.py", line 98, in __getitem__
    return self.dict[k][1]
KeyError: 'backgroundsub'
```

**Comment by ejeschke** [comment]
What happens if you move the call to add the local plugin (only) to pre_gui_config()?

I think we need to fix this, but I'm trying to figure out the dependency order here.

**Comment by pllim** [comment]
If I do that, I do not see the local plugin at all, but I see this in log file:
```
2015-02-11 14:34:00,950 | I | ModuleManager.py:40 (loadModule) | Loading module 'BackgroundSub'...
2015-02-11 14:34:00,959 | E | Control.py:373 (add_local_plugin) | Unable to load local plugin 'BackgroundSub': 'operation'
```

**Comment by ejeschke** [comment]
Could you try one more thing: put all the calls in post_gui_config().  After starting the reference viewer, create a new channel (Channel-> Add Channel).  Switch to the new channel and try to invoke your plugin.  Does it work?

The problem (I'm pretty sure) is the first channel is getting created before the plugin was registered.  So I just need to change the order of initialization to after the call to post_gui_config().

**Comment by ejeschke** [comment]
@pllim, could you try commit 20a724750f7e9b52ac79f5dffc4f49c8ee48d861 ?  Let me know if this fixes the issue.  Tnx.

**Comment by pllim** [comment]
That commit seems to fix my problem. Thank you!

**Comment by ejeschke** [comment]
@pllim, another possibility with a little more flexibility is to make a new startup script like so:
    import sys
    from ginga import main
    from ginga.misc import Bunch

    if __name__ == "__main__":
        spec = Bunch(module='Pipeline', ws='dialogs')
        main.local_plugins.append(spec)
        ...
        main.reference_viewer(sys.argv)

**Comment by pllim** [comment]
@ejeschke , that would be nice if it works because that saves me from distributing the extra `ginga_config.py`. But when I do the following, I get a traceback below.
```
main.global_plugins += [
    Bunch(module='ContentsManager', ws='right'),
    Bunch(module='History', ws='right')]

main.local_plugins += [
    Bunch(module='BackgroundSub', ws='dialogs')]

reference_viewer(...)
```
```
  File ".../lib/python2.7/site-packages/ginga-2.2.20150205225049-py2.7.egg/ginga/main.py", line 446, in reference_viewer
    viewer.add_default_plugins()
  File ".../lib/python2.7/site-packages/ginga-2.2.20150205225049-py2.7.egg/ginga/main.py", line 153, in add_default_plugins
    tab_name=bnch.tab, start_plugin=start)
  File ".../lib/python2.7/site-packages/ginga-2.2.20150205225049-py2.7.egg/ginga/misc/Bunch.py", line 217, in __getattr__
    return self.tbl[attr]
KeyError: 'tab'
```

**Comment by pllim** [comment]
Update: Okay, I got it to work. Turns out I had to explicitly define `tab`, which I didn't have to when using `ginga_config.py`.

**Comment by pllim** [comment]
I think we have beaten this horse to death.

**Comment by ejeschke** [comment]
Poor Horsie.
