### ISSUE TITLE
pip install doesn't

### ISSUE THREAD

**Issue by athornton** [ejeschke/ginga#803]
MacOS 10.14.6, Brew Python 3.7.4

```
adam@air-wired:~$ mkvirtualenv -p $(which python3) ginga
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7'
/usr/local/lib/python2.7/site-packages/virtualenv.py:1047: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /Users/adam/Documents/src/Venvs/ginga/bin/python3.7
Also creating executable in /Users/adam/Documents/src/Venvs/ginga/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/adam/Documents/src/Venvs/ginga/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/adam/Documents/src/Venvs/ginga/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/adam/Documents/src/Venvs/ginga/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/adam/Documents/src/Venvs/ginga/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/adam/Documents/src/Venvs/ginga/bin/get_env_details
(ginga) adam@air-wired:~$ pip install ginga --no-cache
Collecting ginga
  Downloading https://files.pythonhosted.org/packages/a4/f8/0782723e7557bf5b5b6b09c711ad6e757a8e25968d8e025fcc4c1290e155/ginga-3.0.0.tar.gz (22.2MB)
     |██████████████▎                 | 10.0MB 1.5MB/s eta 0:00:0     

[[[ Download progress snipped ]]]

|████████████████████████████████| 22.2MB 1.5MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/adam/Documents/src/Venvs/ginga/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/g5/74rpcxx56x54p7n1nx3wpykh0000gn/T/pip-install-cb6y4hak/ginga/setup.py'"'"'; __file__='"'"'/private/var/folders/g5/74rpcxx56x54p7n1nx3wpykh0000gn/T/pip-install-cb6y4hak/ginga/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/g5/74rpcxx56x54p7n1nx3wpykh0000gn/T/pip-install-cb6y4hak/ginga/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/g5/74rpcxx56x54p7n1nx3wpykh0000gn/T/pip-install-cb6y4hak/ginga/setup.py", line 50, in <module>
        cmdclassd = register_commands()
    TypeError: register_commands() missing 3 required positional arguments: 'package', 'version', and 'release'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by pllim** [comment]
Oh, dear. I can reproduce this on RHEL 7, running `pip install ginga` into a `conda` environment.

**Comment by pllim** [comment]
For reference, here is the diff between tarballs downloaded from PyPI and the one I packaged locally:
```
$ diff -rq from_pypi/ginga-3.0.0 ginga-3.0.0

Files from_pypi/ginga-3.0.0/astropy_helpers/astropy_helpers/version.py and
ginga-3.0.0/astropy_helpers/astropy_helpers/version.py differ

Files from_pypi/ginga-3.0.0/astropy_helpers/astropy_helpers.egg-info/PKG-INFO and
ginga-3.0.0/astropy_helpers/astropy_helpers.egg-info/PKG-INFO differ

Only in ginga-3.0.0/astropy_helpers/astropy_helpers.egg-info: requires.txt

Files from_pypi/ginga-3.0.0/astropy_helpers/astropy_helpers.egg-info/SOURCES.txt and
ginga-3.0.0/astropy_helpers/astropy_helpers.egg-info/SOURCES.txt differ

Files from_pypi/ginga-3.0.0/ginga/version.py and
ginga-3.0.0/ginga/version.py differ

Files from_pypi/ginga-3.0.0/PKG-INFO and
ginga-3.0.0/PKG-INFO differ
```

**Comment by pllim** [comment]
I think I am pretty sure that the PyPI tarball somehow packaged an older version of `astropy-helpers` submodule.

Header from `from_pypi/ginga-3.0.0/astropy_helpers/astropy_helpers.egg-info/PKG-INFO`:
```
Metadata-Version: 1.1
Name: astropy-helpers
Version: 1.2.dev591
```

Header from my local build:
```
Metadata-Version: 2.1
Name: astropy-helpers
Version: 3.2.1
```

**Comment by athornton** [comment]
Doing a `pip install` from GitHub 3.0.0 in a clean virtualenv works.  So it clearly is the PyPi packaging.

Unlike NPM I think PyPi packages are immediately immutable, so the best you can do, I think, is a fast-follower release and delete the 3.0.0 package from PyPi.  I am not entirely sure of that, though.

**Comment by ejeschke** [comment]
I think I did a `python setup.py sdist`, but not `build sdist`.  I guess the _build_ is necessary to generate the proper version file and `astropy-helpers` checkout?  Odd that I haven't encountered this before...

**Comment by ejeschke** [comment]
> Unlike NPM I think PyPi packages are immediately immutable, so the best you can do, I think, is a fast-follower release and delete the 3.0.0 package from PyPi. I am not entirely sure of that, though.

Looks like [that is indeed the case](https://github.com/pypa/packaging-problems/issues/74).

**Comment by ejeschke** [comment]
@athornton, @pllim, I've pushed a 3.0.1 release.  Can you verify that the problem is solved with v3.0.1?  Thanks!

**Comment by pllim** [comment]
Works for me, on Windows no less. Thanks!
```
Successfully installed ginga-3.0.1
```

**Comment by athornton** [comment]
3.0.1 installs fine.  We can close the issue.
